Fb1322
eidolonsystems/clipped_table pull request #1
Opened 2018-12-21 22:09 UTC by spiresheep

2018-12-21 22:31 UTC, kranar requested changes
So far so good.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    if(source > this.rowCount || source < 0) {
If ```source === this.rowCount``` then you should also throw an exception.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    if(destination > this.rowCount || destination < 0) {
Same as above.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    this.values.splice(destination, 0, row.slice());
Don't copy the ```row```.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    if(index > this.rowCount - 1 || index < 0) {
Use ```index >= this.rowCount``` instead of ```index > xxx - 1```.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +      this.dispatcher.dispatch(null);
Don't dispatch a ```null```. A subscriber doesn't care about an error.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    row.values.push(this.values.slice(index, index + 1));
Don't copy the row being removed.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    const table = new ArrayTableModel();
No update is performed here. You will want to actually modify the table itself.

2018-12-21 22:31 UTC, kranar commented on source/array_table_model.ts
> +    if(this.values.length === 1 && this.values[0].length === 0) {
This should strictly evaluate to ```this.values.length```

2018-12-21 22:31 UTC, kranar commented on tests/array_table_model_tester.ts
> +    Expect(model.rowCount).toEqual(0);
You don't need to duplicate all these tests. If this has been tested in another unit test then remove it from this one.

2018-12-21 23:04 UTC, spiresheep commented on source/array_table_model.ts
> +    row.values.push(this.values.slice(index, index + 1));
What should I do instead?

2018-12-24 16:00 UTC, kranar requested changes

2018-12-24 16:00 UTC, kranar commented on source/array_table_model.ts
> +
Remove blank line.

2018-12-24 16:00 UTC, kranar commented on tests/array_table_model_tester.ts
> +  /** Tests removing rows. */
Put blank line between declarations, ie. above line 54.

2018-12-24 16:29 UTC, kranar approved these changes

2018-12-24 16:30 UTC, merged